### PR TITLE
Fix cancellation issues in ReadWriteRef

### LINKED ISSUE #39: Cancelling ReadWriteRef.read can result in a locked-up state
Initially we observed this issue with `FeatureToggled`. It went like so:
- we have a feature-toggled resource, toggled on and under some use
- we toggle it off
- later we toggle it on, but it does not go back.
Heap dumps showed that an internal `rwLock: ReadWriteRef` had a positive number of active tasks despite them being complete long time ago.

We've narrowed down the problem to the incorrect cancellation handling in `ReadWriteRef`, specifically this bit
```scala
val read: Resource[F, A] = {
  Resource.suspend {
    Concurrent.cancelableF[F, Resource[F, A]] { cb =>
      …
      stateRef
        .modify { // acquisition
            …
            val effect = … // emit a Resource that modifies stateRef on release
            val cancel = F.unit
            s1 -> (effect as cancel)
        }
        .flatten
    }
  }
```
In a nutshell, we have two `stateRef` updates here: one for "acquisition" and one for "release", but the problem is that they happen on different "layers", and its quite possible that only "acquisition" happens but not "release" when the `read.use(…)` gets cancelled.

### PR DESCRIPTION
**Pull request by sirmax**
Fixes #39

### CODE REVIEW

File: core/src/main/scala/com/evolutiongaming/catshelper/ReadWriteRef.scala [hunk 1]
```diff
@@ -71,124 +71,166 @@ object ReadWriteRef {
...
-      val write: Resource[F, Upd[F, A]] = {
-        Resource.suspend {
-          Concurrent.cancelableF[F, Resource[F, Upd[F, A]]] { cb =>
-            val listener = (a: A) => {
-              val r = Resource {
-                Ref[F].of(a) map { aRef =>
-                  val upd: Upd[F, A] = (f: A => F[A]) => aRef.get.flatMap(f).flatTap(aRef.set)
-                  val commit = aRef.get.flatMap(a => release(a, _ => 0))
-                  upd -> commit
+    (Ref[F].of(init), Ref[F].of(State())) mapN { (aRef, stateRef) =>
```
Comment (t3hnar) [inline core/src/main/scala/com/evolutiongaming/catshelper/ReadWriteRef.scala:138]: could you please explain on why you need two separate Refs ?

Comment (sirmax) [reply core/src/main/scala/com/evolutiongaming/catshelper/ReadWriteRef.scala:138]: Separation of concerns mostly. I tried to keep the `stateRef` only for read/write coordination to make it easier to understand (at least for myself).

Probably we can fit `a: A` back into the `State` but I'm not sure I want to do this right now. Do you see any problems with a separate ref?
